version: "3.5"
services:
  db:
    image: mongo-db:1.0
    container_name: mongo
    ports: 
      - 27017:27017
    networks: 
      - web_network
  web: 
    container_name: web
    image: go-web:1.0
    ports: 
      - 8000:8000
    env_file:
      - .env
    environment:
      - APP_NAME=hello
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
    depends_on: 
      - db
    networks: 
      - web_network

networks: 
  web_network:
    external: true
    driver: bridge
